name: BoostWeapon
version: '${project.version}'
main: me.iplaygames.boostweapon.SonicWeapon
api-version: '1.20'
commands:
  sonicblast:
    description: Gives the player a sonic bow weapon
  supercharge:
    description: Gives the player a supercharge
  givebroadsword:
      description: Gives the player a broadsword.
  giveharpoongun:
    description: Gives the player a Harpoon gun.
  boostcredits:
    description: Shows plugin credits



